import type en from "@/i18n/dictionaries/en.json";

import type { TripDetailClientLabels } from "./trip-detail-client";

type StorefrontDictionary = typeof en.storefront;

export function buildTripDetailLabels(
  storefront: StorefrontDictionary,
): TripDetailClientLabels {
  const t = storefront.trips;
  const planning = t.local_detail;
  return {
    back: planning.back_to_trips,
    planning: {
      planning_depth: t.planning_depth,
      back_to_trips: planning.back_to_trips,
      share: planning.share,
      export_trip: planning.export_trip,
      collaborative: planning.collaborative,
      route_preview: planning.route_preview,
      route_budget: planning.route_budget,
      daily_itinerary: planning.daily_itinerary,
      map_autoplay: planning.map_autoplay,
      map_travel: planning.map_travel,
      location_selector: t.local.form.location_selector,
      overview_label: planning.overview_label,
      overview_editor: planning.overview_editor,
      fly_to: planning.fly_to,
      stay_in: planning.stay_in,
      day_label: planning.day_label,
      day_unit: planning.day_unit,
      no_stops: planning.no_stops,
      stop_actions: planning.stop_actions,
      place_suggestions: planning.place_suggestions,
      ticket_actions: planning.ticket_actions,
      lodging_stops: planning.lodging_stops,
      edit_title: planning.edit_title,
      title_save_error: planning.title_save_error,
      more: planning.more,
      tabs: planning.tabs,
      add_item: planning.add_item,
      todo_count: planning.todo_count,
      planning_progress: planning.planning_progress,
      explore_stage: planning.explore_stage,
      explore_flights: planning.explore_flights,
      date_range: planning.date_range,
      lumi_takeover: t.lumi.takeover,
      inspiration_explore: {
        title: planning.inspiration_explore.title,
        subtitle: planning.inspiration_explore.subtitle,
        radar_title: planning.inspiration_explore.radar_title,
        radar_subtitle: planning.inspiration_explore.radar_subtitle,
        hero_title: planning.inspiration_explore.hero_title,
        search_placeholder: planning.inspiration_explore.search_placeholder,
        reset_filters: planning.inspiration_explore.reset_filters,
        category_rail_title: planning.inspiration_explore.category_rail_title,
        category_count: planning.inspiration_explore.category_count,
        filter_all: planning.inspiration_explore.filter_all,
        notebook: planning.inspiration_explore.notebook,
        notebook_title: planning.inspiration_explore.notebook_title,
        notebook_empty: planning.inspiration_explore.notebook_empty,
        notebook_map_tab: planning.inspiration_explore.notebook_map_tab,
        want_to_go: planning.inspiration_explore.want_to_go,
        saved_to_notebook: planning.inspiration_explore.saved_to_notebook,
        remove_saved: planning.inspiration_explore.remove_saved,
        confirm_create: planning.inspiration_explore.confirm_create,
        confirming_create: planning.inspiration_explore.confirming_create,
        confirm_empty: planning.inspiration_explore.confirm_empty,
        confirm_error: planning.inspiration_explore.confirm_error,
        details_title: planning.inspiration_explore.details_title,
        select_country: planning.inspiration_explore.select_country,
        selected_country: planning.inspiration_explore.selected_country,
        events: storefront.explore.spotlight_events,
      },
      todo_edit: planning.todo_edit,
      todo_delete: planning.todo_delete,
      todo_save: planning.todo_save,
      todo_cancel: planning.todo_cancel,
      todo_edit_placeholder: planning.todo_edit_placeholder,
      todo_save_error: planning.todo_save_error,
      todo_delete_error: planning.todo_delete_error,
      sections: planning.sections,
      fallback_items: planning.fallback_items,
      kind: planning.kind,
      notes_empty: planning.notes_empty,
      note_editor: planning.note_editor,
      budget_empty: planning.budget_empty,
      budget_analysis: planning.budget_analysis,
      weather: planning.weather,
      journey_live: planning.journey_live,
      lumi_prompt: planning.lumi_prompt,
      map_search: planning.map_search,
      place_details: planning.place_details,
      movement_details: planning.movement_details,
      settings: {
        title: t.settings.title,
        aria: t.settings.aria,
        trip_section: t.settings.trip_section,
        delete_trip: t.settings.delete_trip,
        delete_confirm: t.settings.delete_confirm,
        delete_cancel: t.settings.delete_cancel,
        deleting: t.settings.deleting,
        delete_error: t.settings.delete_error,
      },
      companions: {
        manage_title: t.companions.manage_title,
        manage_aria: t.companions.manage_aria,
        add: t.companions.add,
        rename_placeholder: t.companions.rename_placeholder,
        copy_invite: t.companions.copy_invite,
        email_invite: t.companions.email_invite,
        email_subject: t.companions.email_subject,
        email_body: t.companions.email_body,
        copied: t.companions.copied,
        link_only: t.companions.link_only,
        joined: t.companions.joined,
        delete: t.companions.delete,
        pick_friend: t.companions.pick_friend,
        pick_friend_soon: t.companions.pick_friend_soon,
      },
    },
    notFound: t.detail.not_found,
  };
}
