import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronLeft } from "lucide-react";
import { createSupabaseServerClient } from "@roam/shared";
import { ShopRegionClient } from "@/components/storefront/shop/shop-region-client";
import { findRegionBySlug } from "@/lib/storefront-regions";
import { getDictionary, hasLocale } from "../../../dictionaries";
export const dynamic = "force-dynamic";
export default async function ShopRegionPage({ params, searchParams }: { params: Promise<{ lang: string; region: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) { const { lang, region: regionSlug } = await params; if (!hasLocale(lang)) notFound(); const region = findRegionBySlug(regionSlug); if (!region) notFound(); const dict = await getDictionary(lang); const localeKey: "zh-TW" | "en" = lang === "en" ? "en" : "zh-TW"; const sp = await searchParams; let user: Awaited<ReturnType<Awaited<ReturnType<typeof createSupabaseServerClient>>["auth"]["getUser"]>>["data"]["user"] = null; try { const supabase = await createSupabaseServerClient(); user = (await supabase.auth.getUser()).data.user; } catch { user = null; } const tripId = pickString(sp.trip_id); return <div className="min-h-full pb-28"><header className="relative h-[230px] overflow-hidden"><Image src={region.cover} alt="" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/72 via-black/8 to-black/25" /><Link href={`/${lang}/shop`} aria-label={dict.storefront.shop.back_to_shop} className="absolute left-4 top-24 inline-flex h-10 w-10 items-center justify-center rounded-full bg-surface/90 text-fg shadow-[var(--shadow-card)] backdrop-blur transition-transform duration-150 hover:bg-surface active:scale-[.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ChevronLeft className="h-5 w-5" /></Link><div className="absolute inset-x-0 bottom-0 px-5 pb-5 text-white"><p className="text-[12px] font-medium uppercase tracking-[.14em] text-white/75">{dict.storefront.shop.coverage_label}</p><h1 className="mt-1 truncate text-[30px] font-semibold tracking-[-.03em]">{region.name[localeKey]}</h1><p className="mt-1 truncate text-[13px] text-white/88">{region.destinations.join(" · ")}</p></div></header><ShopRegionClient lang={lang} region={region} labels={dict.storefront.shop} initialDays={pickNum(sp.days)} initialGb={pickNum(sp.gb)} initialCoverageSlugs={pickList(sp.coverage).filter((slug) => Boolean(findRegionBySlug(slug)))} initialQuantity={pickNum(sp.qty)} checkoutTripContext={tripId ? { tripId, checklistItemId: pickString(sp.checklist_id) } : null} checkoutProfile={user ? { email: user.email ?? "", name: typeof user.user_metadata?.full_name === "string" ? user.user_metadata.full_name : "" } : null} /></div>; }
function pickString(value: string | string[] | undefined) { const item = Array.isArray(value) ? value[0] : value; return item?.trim() || undefined; }
function pickNum(value: string | string[] | undefined) { const number = Number(pickString(value)); return Number.isFinite(number) ? number : undefined; }
function pickList(value: string | string[] | undefined) { return (Array.isArray(value) ? value : value ? [value] : []).flatMap((item) => item.split(",")).map((item) => item.trim()).filter(Boolean); }
