import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, MapPin } from "lucide-react";
import { ShopSearchPill } from "@/components/storefront/shop/shop-search-pill";
import { REGION_GROUPS, findRegionBySlug, type ShopRegion } from "@/lib/storefront-regions";
import { getDictionary, hasLocale } from "../../dictionaries";
export const dynamic = "force-dynamic";
export default async function ShopPage({ params }: { params: Promise<{ lang: string }> }) { const { lang } = await params; if (!hasLocale(lang)) notFound(); const dict = await getDictionary(lang); const labels = dict.storefront.shop; const localeKey: "zh-TW" | "en" = lang === "en" ? "en" : "zh-TW"; return <div className="min-h-full pb-28 pt-20 md:pt-24"><header className="mx-auto max-w-[980px] px-5"><p className="text-[12px] font-medium uppercase tracking-[.14em] text-accent">Roam eSIM</p><h1 className="mt-2 text-balance text-[30px] font-semibold tracking-[-.03em] text-fg sm:text-[38px]">{labels.title}</h1><p className="mt-2 max-w-lg text-[15px] leading-6 text-fg-muted">{labels.subtitle}</p></header><div className="mx-auto mt-7 max-w-[980px]"><ShopSearchPill lang={lang} localeKey={localeKey} labels={labels} stats={{}}><div className="mt-8 space-y-10 px-5">{REGION_GROUPS.slice(0, 3).map((group) => <section key={group.id}><div className="mb-3 flex items-center justify-between"><h2 className="text-[17px] font-semibold tracking-[-.01em] text-fg">{group.name[localeKey]}</h2><span className="text-[12px] text-fg-muted">{group.slugs.length}</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{group.slugs.map(findRegionBySlug).filter((region): region is ShopRegion => Boolean(region)).map((region) => <RegionCard key={region.slug} lang={lang} localeKey={localeKey} region={region} />)}</div></section>)}</div></ShopSearchPill></div></div>; }
function RegionCard({ lang, localeKey, region }: { lang: string; localeKey: "zh-TW" | "en"; region: ShopRegion }) { return <Link href={`/${lang}/shop/${region.slug}`} className="group relative min-h-36 overflow-hidden rounded-3xl bg-surface shadow-[var(--shadow-card)] transition-[transform,box-shadow] duration-180 hover:-translate-y-0.5 hover:shadow-[var(--shadow-md)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-4"><Image src={region.cover} alt="" fill sizes="(max-width: 640px) 50vw, 300px" className="object-cover transition-transform duration-[260ms] group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/8 to-transparent" /><div className="absolute inset-x-0 bottom-0 flex items-end gap-2 p-3 text-white"><MapPin className="mb-0.5 h-4 w-4 shrink-0" aria-hidden="true" /><span className="min-w-0 flex-1 truncate text-[15px] font-semibold">{region.name[localeKey]}</span><ArrowRight className="h-4 w-4 shrink-0 transition-transform duration-150 group-hover:translate-x-0.5" aria-hidden="true" /></div></Link>; }
