/**
 * The spotlight events Explore rotates through.
 *
 * Lifted out of the component so the route contract over them can be tested without
 * rendering React: `regionSlug` here is EDITORIAL — it names the place in prose — and
 * is NOT a /shop slug. Seven of these ("singapore", "brazil", "taiwan", "malaysia")
 * are not in SHOP_REGIONS at all, and linking to them produced a 404. `countryCode`
 * is the ISO code, and resolving THAT through buildShopHref is the only way to reach
 * the canonical region page.
 *
 * spotlight-events.contract.test.ts asserts every event still resolves.
 */
export const SPOTLIGHT_EVENTS = [
  {
    id: "venice-carnival",
    regionSlug: "italy",
    countryCode: "IT",
    image: "/illustrations/cities/rome.jpg",
    lat: 45.44,
    lng: 12.315,
    tone: "coral",
  },
  {
    id: "rio-carnival",
    regionSlug: "brazil",
    countryCode: "BR",
    image: "/illustrations/cities/rio.jpg",
    lat: -22.906,
    lng: -43.172,
    tone: "green",
  },
  {
    id: "tomorrowland",
    regionSlug: "belgium",
    countryCode: "BE",
    image: "/illustrations/cities/europe.jpg",
    lat: 51.09,
    lng: 4.37,
    tone: "violet",
  },
  {
    id: "iceland-lights",
    regionSlug: "iceland",
    countryCode: "IS",
    image: "/illustrations/timeline/seasons/winter.png",
    lat: 64.147,
    lng: -21.942,
    tone: "violet",
  },
  {
    id: "singapore-grand-prix",
    regionSlug: "singapore",
    countryCode: "SG",
    image: "/illustrations/cities/singapore.jpg",
    lat: 1.291,
    lng: 103.864,
    tone: "cyan",
  },
  {
    id: "taiwan-lantern",
    regionSlug: "taiwan",
    countryCode: "TW",
    image: "/illustrations/cities/taipei.jpg",
    lat: 23.697,
    lng: 120.96,
    tone: "gold",
  },
  {
    id: "taiwan-mazu",
    regionSlug: "taiwan",
    countryCode: "TW",
    image: "/illustrations/events/taiwan-dajia-mazu-pilgrimage.png",
    lat: 24.347,
    lng: 120.623,
    tone: "coral",
  },
  {
    id: "japan-gion",
    regionSlug: "japan",
    countryCode: "JP",
    image: "/illustrations/cities/kyoto.jpg",
    lat: 35.011,
    lng: 135.768,
    tone: "rose",
  },
  {
    id: "fuji-rock",
    regionSlug: "japan",
    countryCode: "JP",
    image: "/illustrations/events/japan-fuji-rock-2026.png",
    lat: 36.79,
    lng: 138.78,
    tone: "violet",
  },
  {
    id: "jp-sakura",
    regionSlug: "japan",
    countryCode: "JP",
    image: "/illustrations/events/jp-sakura-2026.png",
    lat: 35.011,
    lng: 135.768,
    tone: "rose",
  },
  {
    id: "korankei-autumn",
    regionSlug: "japan",
    countryCode: "JP",
    image: "/illustrations/events/japan-korankei-autumn-festival.png",
    lat: 35.133,
    lng: 137.316,
    tone: "gold",
  },
  {
    id: "korea-boryeong-mud",
    regionSlug: "korea",
    countryCode: "KR",
    image: "/illustrations/events/korea-boryeong-mud-festival-2026.png",
    lat: 36.305,
    lng: 126.517,
    tone: "coral",
  },
  {
    id: "korea-jinhae-cherry",
    regionSlug: "korea",
    countryCode: "KR",
    image: "/illustrations/events/korea-jinhae-gunhangje-cherry-blossom.png",
    lat: 35.15,
    lng: 128.66,
    tone: "rose",
  },
  {
    id: "hong-kong-sevens",
    regionSlug: "hong-kong",
    countryCode: "HK",
    image: "/illustrations/events/hong-kong-sevens-2026.png",
    lat: 22.278,
    lng: 114.182,
    tone: "cyan",
  },
  {
    id: "hong-kong-flower-show",
    regionSlug: "hong-kong",
    countryCode: "HK",
    image: "/illustrations/events/hong-kong-flower-show.png",
    lat: 22.281,
    lng: 114.188,
    tone: "rose",
  },
  {
    id: "rainforest-world-music",
    regionSlug: "malaysia",
    countryCode: "MY",
    image: "/illustrations/events/malaysia-rainforest-world-music-festival-2026.png",
    lat: 1.744,
    lng: 110.315,
    tone: "green",
  },
  {
    id: "singapore-durian",
    regionSlug: "singapore",
    countryCode: "SG",
    image: "/illustrations/events/singapore-malaysia-durian-season.png",
    lat: 1.352,
    lng: 103.819,
    tone: "green",
  },
  {
    id: "taipei-feast",
    regionSlug: "taiwan",
    countryCode: "TW",
    image: "/illustrations/events/taipei-taipei-feast-2026.png",
    lat: 25.033,
    lng: 121.565,
    tone: "coral",
  },
] as const;
