import type { ShopRegion } from "@/lib/storefront-region-types";

export const EUROPE_COUNTRY_REGIONS: ShopRegion[] = [
  { slug: "austria", name: { "zh-TW": "奧地利", en: "Austria" }, destinations: ["AT"], aliases: ["Vienna", "Wien", "維也納"], cover: "/illustrations/cities/vienna.jpg" },
  { slug: "belgium", name: { "zh-TW": "比利時", en: "Belgium" }, destinations: ["BE"], aliases: ["Brussels", "Bruges", "布魯塞爾", "布魯日"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "bulgaria", name: { "zh-TW": "保加利亞", en: "Bulgaria" }, destinations: ["BG"], aliases: ["Sofia", "索菲亞"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "croatia", name: { "zh-TW": "克羅埃西亞", en: "Croatia" }, destinations: ["HR"], aliases: ["Zagreb", "Dubrovnik", "札格雷布", "杜布羅夫尼克"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "cyprus", name: { "zh-TW": "賽普勒斯", en: "Cyprus" }, destinations: ["CY"], aliases: ["Nicosia", "尼科西亞"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "czechia", name: { "zh-TW": "捷克", en: "Czechia" }, destinations: ["CZ"], aliases: ["Czech Republic", "Prague", "布拉格"], cover: "/illustrations/cities/prague.jpg" },
  { slug: "denmark", name: { "zh-TW": "丹麥", en: "Denmark" }, destinations: ["DK"], aliases: ["Copenhagen", "哥本哈根"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "estonia", name: { "zh-TW": "愛沙尼亞", en: "Estonia" }, destinations: ["EE"], aliases: ["Tallinn", "塔林"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "finland", name: { "zh-TW": "芬蘭", en: "Finland" }, destinations: ["FI"], aliases: ["Helsinki", "赫爾辛基"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "france", name: { "zh-TW": "法國", en: "France" }, destinations: ["FR"], aliases: ["Paris", "Nice", "Lyon", "巴黎", "尼斯", "里昂"], cover: "/illustrations/cities/paris.jpg" },
  { slug: "germany", name: { "zh-TW": "德國", en: "Germany" }, destinations: ["DE"], aliases: ["Berlin", "Munich", "Frankfurt", "柏林", "慕尼黑", "法蘭克福"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "greece", name: { "zh-TW": "希臘", en: "Greece" }, destinations: ["GR"], aliases: ["Athens", "Santorini", "雅典", "聖托里尼"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "hungary", name: { "zh-TW": "匈牙利", en: "Hungary" }, destinations: ["HU"], aliases: ["Budapest", "布達佩斯"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "ireland", name: { "zh-TW": "愛爾蘭", en: "Ireland" }, destinations: ["IE"], aliases: ["Dublin", "都柏林"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "italy", name: { "zh-TW": "義大利", en: "Italy" }, destinations: ["IT"], aliases: ["Rome", "Roma", "Milan", "Venice", "Florence", "羅馬", "米蘭", "威尼斯", "佛羅倫斯"], intro: { "zh-TW": "古城、海岸與美食季節交錯，從羅馬一路走進托斯卡尼與南義。", en: "Ancient cities, coastal escapes, and food seasons from Rome to Tuscany and the south." }, cover: "/illustrations/cities/rome.jpg" },
  { slug: "latvia", name: { "zh-TW": "拉脫維亞", en: "Latvia" }, destinations: ["LV"], aliases: ["Riga", "里加"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "lithuania", name: { "zh-TW": "立陶宛", en: "Lithuania" }, destinations: ["LT"], aliases: ["Vilnius", "維爾紐斯"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "luxembourg", name: { "zh-TW": "盧森堡", en: "Luxembourg" }, destinations: ["LU"], aliases: ["Luxembourg City", "盧森堡市"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "malta", name: { "zh-TW": "馬爾他", en: "Malta" }, destinations: ["MT"], aliases: ["Valletta", "瓦萊塔"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "netherlands", name: { "zh-TW": "荷蘭", en: "Netherlands" }, destinations: ["NL"], aliases: ["Holland", "Amsterdam", "阿姆斯特丹"], cover: "/illustrations/cities/amsterdam.jpg" },
  { slug: "poland", name: { "zh-TW": "波蘭", en: "Poland" }, destinations: ["PL"], aliases: ["Warsaw", "Krakow", "華沙", "克拉科夫"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "portugal", name: { "zh-TW": "葡萄牙", en: "Portugal" }, destinations: ["PT"], aliases: ["Lisbon", "Porto", "里斯本", "波多"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "romania", name: { "zh-TW": "羅馬尼亞", en: "Romania" }, destinations: ["RO"], aliases: ["Bucharest", "布加勒斯特"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "slovakia", name: { "zh-TW": "斯洛伐克", en: "Slovakia" }, destinations: ["SK"], aliases: ["Bratislava", "布拉提斯拉瓦"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "slovenia", name: { "zh-TW": "斯洛維尼亞", en: "Slovenia" }, destinations: ["SI"], aliases: ["Ljubljana", "Bled", "盧布里雅納", "布萊德湖"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "spain", name: { "zh-TW": "西班牙", en: "Spain" }, destinations: ["ES"], aliases: ["Barcelona", "Madrid", "Camino", "巴塞隆納", "馬德里", "朝聖之路"], cover: "/illustrations/cities/barcelona.jpg" },
  { slug: "sweden", name: { "zh-TW": "瑞典", en: "Sweden" }, destinations: ["SE"], aliases: ["Stockholm", "斯德哥爾摩"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "united-kingdom", name: { "zh-TW": "英國", en: "United Kingdom" }, destinations: ["GB"], aliases: ["UK", "Britain", "London", "Scotland", "倫敦", "蘇格蘭"], cover: "/illustrations/cities/london.jpg" },
  { slug: "norway", name: { "zh-TW": "挪威", en: "Norway" }, destinations: ["NO"], aliases: ["Oslo", "Bergen", "奧斯陸", "卑爾根"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "switzerland", name: { "zh-TW": "瑞士", en: "Switzerland" }, destinations: ["CH"], aliases: ["Zurich", "Geneva", "Zermatt", "蘇黎世", "日內瓦", "策馬特"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "iceland", name: { "zh-TW": "冰島", en: "Iceland" }, destinations: ["IS"], aliases: ["Reykjavik", "雷克雅維克"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "liechtenstein", name: { "zh-TW": "列支敦士登", en: "Liechtenstein" }, destinations: ["LI"], aliases: ["Vaduz", "瓦杜茲"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "serbia", name: { "zh-TW": "塞爾維亞", en: "Serbia" }, destinations: ["RS"], aliases: ["Belgrade", "貝爾格勒"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "bosnia-herzegovina", name: { "zh-TW": "波士尼亞與赫塞哥維納", en: "Bosnia & Herzegovina" }, destinations: ["BA"], aliases: ["Bosnia", "Sarajevo", "Mostar", "塞拉耶佛", "莫斯塔爾"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "montenegro", name: { "zh-TW": "蒙特內哥羅", en: "Montenegro" }, destinations: ["ME"], aliases: ["Kotor", "Podgorica", "科托爾"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "north-macedonia", name: { "zh-TW": "北馬其頓", en: "North Macedonia" }, destinations: ["MK"], aliases: ["Skopje", "Ohrid", "史高比耶", "奧赫里德"], cover: "/illustrations/cities/europe.jpg" },
  { slug: "albania", name: { "zh-TW": "阿爾巴尼亞", en: "Albania" }, destinations: ["AL"], aliases: ["Tirana", "提拉那"], cover: "/illustrations/cities/europe.jpg" },
].map((region) => ({
  ...region,
  esimRegionSlug: "europe",
  introOnly: true,
}));

export const EUROPE_COUNTRY_REGION_SLUGS = EUROPE_COUNTRY_REGIONS.map(
  (region) => region.slug,
);
